// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY_lhCEmtRi3O3JB7oPqXEE1grFqkFUWk',
    appId: '1:537739658446:web:969cf6f3eec75edf663c9f',
    messagingSenderId: '537739658446',
    projectId: 'tiktok-clone-93465',
    authDomain: 'tiktok-clone-93465.firebaseapp.com',
    storageBucket: 'tiktok-clone-93465.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgtXNpsWwJpujML66E17z1u92XryJwUGA',
    appId: '1:537739658446:android:3e707ed88acd1178663c9f',
    messagingSenderId: '537739658446',
    projectId: 'tiktok-clone-93465',
    storageBucket: 'tiktok-clone-93465.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQfKHGBtom2QgJpkndltHscUShHqV48nA',
    appId: '1:537739658446:ios:e9ffdec161eb4f24663c9f',
    messagingSenderId: '537739658446',
    projectId: 'tiktok-clone-93465',
    storageBucket: 'tiktok-clone-93465.appspot.com',
    iosClientId: '537739658446-gcpmm827fg2un071thnti6sjm0c2ah2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQfKHGBtom2QgJpkndltHscUShHqV48nA',
    appId: '1:537739658446:ios:6ccd02e647864b7d663c9f',
    messagingSenderId: '537739658446',
    projectId: 'tiktok-clone-93465',
    storageBucket: 'tiktok-clone-93465.appspot.com',
    iosClientId: '537739658446-8l2u2bh42qrfap20011sfko55odbrb38.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
